ekrubrygg/recipe/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('<int:recipe_id>/', views.detail, name='detail'),
    path('<int:recipe_id>/edit/', views.edit, name='edit'),

    path('my_recipes/', views.created_recipes, name='created_recipes'),
    path('my_ingredients/', views.created_ingredients, name='created_ingredients'),
    path('my_ingredients/<int:ingredient_id>/', views.edit_ingredient, name='edit_ingredient'),
    path('add/', views.add, name='add'),

    path('<int:recipe_id>/delete/', views.delete, name='delete'),
    path('<int:recipe_id>/delete/step/<int:step_id>/', views.delete_step, name='delete_step'),
    path('<int:recipe_id>/delete/ingredient/<int:ingredient_id>/', views.delete_ingredient_from_recipe, name='delete_ingredient_from_recipe'),
    path('<int:recipe_id>/delete/step/ingredient/<int:step_ingredient_id>/', views.delete_ingredient_from_step, name='delete_ingredient_from_step'),
    path('<int:recipe_id>/move/<int:step_id>/', views.move_step, name='move_step'),
    path('<int:recipe_id>/publicize/', views.publicize, name='publicize'),
    path('<int:recipe_id>/add_step/', views.add_step, name='add_step'),
    path('<int:recipe_id>/ingredient/<str:action>', views.add_ingredient_to_recipe, name='add_ingredient_to_recipe'),
    path('<int:recipe_id>/edit/ingredient/<int:ingredient_id>/', views.edit_ingredient_in_recipe, name='edit_ingredient_in_recipe'),
    path('<int:recipe_id>/edit/step/<int:step_id>/', views.edit_step_description, name='edit_step_description'),

    path('ingredient/<str:action>', views.add_ingredient, name='add_ingredient'),

    path('<str:brew_type>/', views.brew_filter, name='brew_filter'),
]

ekrubrygg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from .core.urls import urlpatterns as core_urls
from .recipe.urls import urlpatterns as recipe_urls
from .account.urls import urlpatterns as account_urls

from .account.views import profile as profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_urls)),
    path('recipe/', include((recipe_urls, 'recipe'), namespace='recipe')),
    path('accounts/profile/', profile_view, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ekrubrygg/recipe/models.py
from math import fsum

from django.db import models
from django.conf import settings

from ordered_model.models import OrderedModel
from tinymce import HTMLField

class Recipe(models.Model):
    name = models.CharField(max_length=99)
    brew_category = models.ForeignKey('BrewCategory', null=True, on_delete=models.SET_NULL)
    public = models.BooleanField(default=False)
    original_gravity = models.FloatField(blank=True, null=True)
    final_gravity = models.FloatField(blank=True, null=True)
    ph = models.FloatField(blank=True, null=True)
    ingredients = models.ManyToManyField('Ingredient', through='IngredientInRecipe', name='ingredients', related_name='recipe')
    pub_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.name

    def calculate_abv(self):
        if self.original_gravity and self.final_gravity:
            return '{0:.2f}'.format((self.original_gravity - self.final_gravity) * self.brew_category.abv_factor)
        else:
            return 'Add both OG and FG to get ABV.'


class BrewCategory(models.Model):
    name = models.CharField(max_length=99)
    category = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
    abv_factor = models.FloatField()

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=99)
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey('IngredientCategory', on_delete=models.CASCADE)
    manufacturer = models.ForeignKey('Manufacturer', related_name='ingredient', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = ['name', 'manufacturer', 'created_by']

    def __str__(self):
        return '%s by %s' % (self.name, self.manufacturer.name)


class IngredientCategory(models.Model):
    name = models.CharField(max_length=99)
    category = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class IngredientInRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, related_name='in_recipe', on_delete=models.CASCADE)
    amount = models.FloatField()
    amount_unit = models.ForeignKey('AmountUnit', null=True, on_delete=models.SET_NULL)
    step = models.ManyToManyField('Step', through='IngredientInStep', name='steps', related_name='ingredient_in_recipe')

    def __str__(self):
        return '%s by %s' % (self.ingredient.name, self.ingredient.manufacturer.name)

    def amount_left(self):
        return self.amount - fsum([x.amount for x in self.ingredientinstep_set.all()])

    def get_amount(self):
        if self.amount == int(self.amount):
            return int(self.amount)
        else:
            return self.amount


class IngredientInStep(models.Model):
    ingredient = models.ForeignKey(IngredientInRecipe, on_delete=models.CASCADE)
    step = models.ForeignKey('Step', on_delete=models.CASCADE)
    amount = models.FloatField()

    def __str__(self):
        return self.ingredient

    def get_amount(self):
        if self.amount == int(self.amount):
            return int(self.amount)
        else:
            return self.amount


class AmountUnit(models.Model):
    name = models.CharField(max_length=36)
    unit_of = models.CharField(max_length=1,
                               choices=[('V', 'Volume'),
                                        ('W', 'Weight')],
                               default='V')
    system = models.CharField(max_length=1,
                               choices=[('M', 'Metric'),
                                        ('I', 'Imperial')],
                               default='M')

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=99)
    website = models.URLField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


class Step(OrderedModel):
    # For class Meta use: class Meta(OrderedModel.Meta)
    category = models.ForeignKey('StepCategory', null=True, on_delete=models.SET_NULL)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    duration = models.DurationField()
    description = HTMLField('Description', blank=True, null=True)

    order_with_respect_to = 'recipe'

    def __str__(self):
        return '%i %s in %s' % (self.order + 1, self.category.name, self.recipe.name)

    def _add_time(self, value, append):
        if self.time_output and value:
            self.time_output += ', {} {}'.format(value, append)
        elif value:
            self.time_output = '{} {}'.format(value, append)

    def format_duration(self):
        self.time_output = None
        total_minutes = self.duration.seconds // 60
        self._add_time(self.duration.days, 'days')
        self._add_time((total_minutes // 60), 'hours')
        self._add_time((total_minutes % 60), 'minutes')
        return self.time_output


class StepCategory(models.Model):
    name = models.CharField(max_length=99)
    category = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

ekrubrygg/recipe/forms.py
from datetime import timedelta

from django.forms import ModelForm, NumberInput, URLField, CharField, ModelChoiceField, ChoiceField, IntegerField, Textarea
from django.core.exceptions import ValidationError

from .models import Recipe, Ingredient, IngredientInRecipe, IngredientInStep, IngredientCategory, Manufacturer, StepCategory, Step
from .fields import IntDurationField


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        exclude = ('public', 'ingredients', 'pub_date', 'created_by')
        widgets = {
            'original_gravity': NumberInput(attrs={'step': '0.001',
                                                   'value': '1.099'}),
            'final_gravity': NumberInput(attrs={'step': '0.001',
                                                'value': '1.000'})}


class StepForm(ModelForm):
    duration = IntegerField()
    duration_type = ChoiceField(choices=[('M', 'Minutes'),
                                         ('H', 'Hours'),
                                         ('D', 'Days')])

    class Meta:
        model = Step
        exclude = ('recipe',)

    def clean(self):
        cleaned_data = super().clean()
        duration = cleaned_data.get('duration')
        duration_type = cleaned_data.get('duration_type')
        if duration_type == 'M':
            cleaned_data['duration'] = timedelta(minutes=duration)
        elif duration_type == 'H':
            cleaned_data['duration'] = timedelta(hours=duration)
        elif duration_type == 'D':
            cleaned_data['duration'] = timedelta(days=duration)
        else:
            raise ValidationError('Invalid duration type!', code='invalid')
        return cleaned_data


class IngredientForm(ModelForm):
    manufacturer = CharField(max_length=99, min_length=2, strip=True)
    manufacturer_website = URLField(required=False, help_text='Not required')

    class Meta:
        model = Ingredient
        exclude = ('created_by',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(IngredientForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        
        manufacturer = Manufacturer.objects.get_or_create(
            name=self.cleaned_data['manufacturer'],
            created_by=self.user
        )
        if cleaned_data['manufacturer_website']:
            manufacturer[0].website = cleaned_data['manufacturer_website']

        cleaned_data['manufacturer'] = manufacturer[0]

        print('\n\n')
        print('%s\n%s' % (manufacturer[1], self.instance.manufacturer.ingredient.all()))
        print('\n\n')
        # Delete manufacturer if it doesn't belong to any ingredients after change of model
        if hasattr(self.instance, 'manufacturer') and self.instance.manufacturer.ingredient.all().count() == 1:
            print('\n\n')
            print('Is it going inside if?')
            print('\n\n')
            self.instance.manufacturer.delete()

        return cleaned_data


class IngredientInRecipeForm(ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    name = CharField(max_length=99, min_length=2, strip=True)
    manufacturer = CharField(max_length=99, min_length=2, strip=True)
    manufacturer_website = URLField(required=False)
    description = CharField(min_length=2, strip=True, widget=Textarea(), required=False)
    category = ModelChoiceField(queryset=IngredientCategory.objects.all())

    field_order = ['name']

    class Meta:
        model = IngredientInRecipe
        exclude = ('recipe', 'ingredient', 'steps')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(IngredientInRecipeForm, self).__init__(*args, **kwargs)
        self.fields['amount_unit'].empty_label = None
        self.fields['amount_unit'].label = ''

    def clean(self):
        cleaned_data = super().clean()
        manufacturer = Manufacturer.objects.get_or_create(
            name=cleaned_data['manufacturer'],
            created_by=self.user
        )
        if cleaned_data['manufacturer_website']:
            manufacturer[0].website = cleaned_data['manufacturer_website']

        # Delete manufacturer if it doesn't belong to any ingredients after change of model
        if hasattr(self.instance, 'ingredient') and self.instance.ingredient.manufacturer.ingredient_set.all().count() == 1:
            self.instance.ingredient.manufacturer.delete()

        ingredient = Ingredient.objects.get_or_create(
            name=cleaned_data['name'],
            created_by=self.user,
            manufacturer=manufacturer[0],
            category=cleaned_data['category']
        )

        # Delete ingredient if it doesn't belong to any recipe after change of model
        if hasattr(self.instance, 'ingredient') and self.instance.ingredient.ingredientinrecipe_set.all().count() == 1:
            self.instance.ingredient.delete()

        cleaned_data['ingredient'] = ingredient[0]
        self.instance.ingredient = ingredient[0]

        return cleaned_data


class IngredientSelectField(ModelChoiceField):
    def label_from_instance(self, obj):
        return "%s by %s (%s)" % (obj.ingredient.name, obj.ingredient.manufacturer.name, obj.amount_unit)


class IngredientInStepForm(ModelForm):
    ingredient = IngredientSelectField(queryset=IngredientInRecipe.objects.all())

    class Meta:
        model = IngredientInStep
        exclude = ('step',)

    def __init__(self, recipe, *args, **kwargs):
        super(IngredientInStepForm, self).__init__(*args, **kwargs)
        self.fields['ingredient'].queryset = self.fields['ingredient'].queryset.filter(recipe=recipe)
        self.fields['ingredient'].empty_label = 'Choose ingredient'


class StepDescriptionForm(ModelForm):
    class Meta:
        model = Step
        fields = ('description',)

templates/recipe/add_ingredient_form.html
{% extends "base.html" %}

{% block title %}
  {{ block.super }} - {{ title }}
{% endblock %}

{% block javascripts %}
  {% include "includes/jquery.html" %}
  <!-- https://jqueryui.com/autocomplete/#custom-data -->
  <script>
  $( function() {
    var availableManufacturers = [
      {% for i in available_manufacturers %}
        "{{ i|safe }}",
      {% endfor %}
    ];
    $( "#id_manufacturer" ).autocomplete({
      source: availableManufacturers
    });

    var availableIngredients = [
      {% for i in available_ingredients %}
        "{{ i|safe }}",
      {% endfor %}
    ];
    $( "#id_name" ).autocomplete({
      source: availableIngredients
    });
  });
  </script>
{% endblock %}

{% block sub_nav %}
  {% include "recipe/nav.html" %}
{% endblock %}

{% block content %}
  <form method="post" action="{% url 'recipe:add_ingredient' 'add' %}">
		{% csrf_token %}
		{{ form.as_ul }}
		<input type="submit" value="Create"/>
    <input type="submit" formaction="{% url 'recipe:add_ingredient' 'more' %}" value="Add more"/>
	</form> 
  <a href="{% url 'recipe:created_ingredients' %}">Cancel</a>
  <p>Is there a missing ingredient category you would like to add? Then {% include "includes/feature_request.html" %}
  <br>In the meanwhile just put it in the misc category.</p>
{% endblock %}

templates/recipe/add_ingredient_to_recipe_form.html
{% extends "base.html" %}

{% block title %}
  {{ block.super }} - {{ title }}
{% endblock %}

{% block javascripts %}
  {% include "includes/jquery.html" %}
  <!-- https://jqueryui.com/autocomplete/#custom-data -->
  <script>
  $( function() {
    var availableManufacturers = [
      {% for i in available_manufacturers %}
        "{{ i|safe }}",
      {% endfor %}
    ];
    $( "#id_manufacturer" ).autocomplete({
      source: availableManufacturers
    });

    var availableIngredients = [
      {% for i in available_ingredients %}
        "{{ i.name|safe }}",
      {% endfor %}
    ];
    $( "#id_name" ).autocomplete({
      source: availableIngredients
    });
  });
  </script>
{% endblock %}

{% block sub_nav %}
  {% include "recipe/nav.html" %}
{% endblock %}

{% block content %}
  <form method="post" action="{% url 'recipe:add_ingredient_to_recipe' recipe_id 'add' %}">
		{% csrf_token %}
		{{ form.as_ul }}
		<input type="submit" value="Create"/>
    <input type="submit" formaction="{% url 'recipe:add_ingredient_to_recipe' recipe_id 'more' %}" value="Add more"/>
	</form> 
  <a href="{% url 'recipe:detail' recipe_id %}">Cancel</a>
  <p>Is there a missing ingredient category you would like added? Then {% include "includes/feature_request.html" %}
  <br>In the meanwhile just put it in the misc category.</p>
{% endblock %}

templates/recipe/created_ingredients.html
{% extends "base.html" %}

{% block title %}
  {{ block.super }} - {{ title }}
{% endblock %}

{% block center_nav %}
  <li>
    <a href="{% url 'recipe:add_ingredient' 'add' %}">Add ingredient</a>
  </li>
{% endblock %}

{% block content %}
	{% if ingredients %}
		<ul>
		{% for ingredient in ingredients %}
      <li class="small_box">
        <h2>{{ ingredient.name }}</h2>
        <p><b>{{ ingredient.category }}</b></p>
        {% if ingredient.manufacturer.website %}
          <p><i><a href="{{ ingredient.manufacturer.website }}">Manufactured by {{ ingredient.manufacturer }}</a></i></p>
        {% else %}
          <p><i>Manufactured by {{ ingredient.manufacturer }}</i></p>
        {% endif %}
        <p>{{ ingredient.description }}</p>
        <a href="{% url 'recipe:edit_ingredient' ingredient.id %}">Edit</a>
        <ul>
          {% if ingredient.recipe.all %}
            <h3>Previously used in</h3>
            {% for recipe in ingredient.recipe.all %}
              <li><a href="{% url 'recipe:detail' recipe.id %}">{{ recipe.name }}</a></li>
            {% endfor %}
          {% endif %}
        </ul>
      </li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No ingredients created by you yet!</p>
	{% endif %}
{% endblock %}

templates/recipe/created_recipes.html
{% extends "base.html" %}

{% block title %}
{{ block.super }} - {{ title }}
{% endblock %}

{% block center_nav %}
    <li>
      <a href="{% url 'recipe:add' %}">Add recipe</a>
    </li>
{% endblock %}

{% block content %}
	{% if recipes %}
    <section>
      <ul id="created_recipes">
      {% for recipe in recipes %}
        <li>
          <h4><a href="{% url 'recipe:detail' recipe.id %}">{{ recipe.name }}</a></h4>
          <h5>Published {{ recipe.pub_date }} by {{ recipe.created_by }}</h5>
        </li>
      {% endfor %}
      </ul>
    </section>
	{% else %}
    <section>
      <p>No recipes created by you yet!</p>
    </section>
	{% endif %}
{% endblock %}

templates/recipe/edit_form.html
{% extends "base.html" %}

{% block title %}
  {{ block.super }} - {{ title }}
{% endblock %}

{% block javascripts %}
  {% include "includes/jquery.html" %}
  <!-- https://jqueryui.com/autocomplete/#custom-data -->
  <script>
  $( function() {
    var availableManufacturers = [
      {% for i in available_manufacturers %}
        "{{ i|safe }}",
      {% endfor %}
    ];
    $( "#id_manufacturer" ).autocomplete({
      source: availableManufacturers
    });

    var availableIngredients = [
      {% for i in available_ingredients %}
        "{{ i.name|safe }}",
      {% endfor %}
    ];
    $( "#id_name" ).autocomplete({
      source: availableIngredients
    });
  });
  </script>
{% endblock %}

{% block sub_nav %}
  {% include "recipe/nav.html" %}
{% endblock %}

{% block content %}
  <form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Edit"/>
	</form>
{% endblock %}

templates/recipe/edit_ingredient_form.html
{% extends "base.html" %}

{% block title %}
  {{ block.super }} - {{ title }}
{% endblock %}

{% block javascripts %}
  {% include "includes/jquery.html" %}
  <!-- https://jqueryui.com/autocomplete/#custom-data -->
  <script>
  $( function() {
    var availableManufacturers = [
      {% for i in available_manufacturers %}
        "{{ i|safe }}",
      {% endfor %}
    ];
    $( "#id_manufacturer" ).autocomplete({
      source: availableManufacturers
    });

    var availableIngredients = [
      {% for i in available_ingredients %}
        "{{ i.name|safe }}",
      {% endfor %}
    ];
    $( "#id_name" ).autocomplete({
      source: availableIngredients
    });
  });
  </script>
{% endblock %}

{% block sub_nav %}
  {% include "recipe/nav.html" %}
{% endblock %}

{% block content %}
<section class="small_box">
  <form method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Edit"/>
	</form>
</section>
{% endblock %}

templates/recipe/edit_recipe.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ block.super }} - {{ recipe.name }}
{% endblock %}

{% block javascripts %}
  {% include "includes/jquery.html" %}
  <script src="{% static 'js/brew_details.js' %}"></script>
  {{ step_description_form.media }}
{% endblock %}

{% block admin_nav %}
  {% if user == recipe.created_by %}
    <nav class="admin">
        <ul>
          <li>
            <a class="txt-btn" href="{% url 'recipe:detail' recipe.id %}">View</a>
          </li>
          <li>
            {% include "includes/recipe/forms/publicize_recipe.html" %}
          </li>
        </ul>
        <ul>
          <li>
            <a class="txt-btn" href="{% url 'recipe:add_ingredient_to_recipe' recipe.id 'add' %}">Add ingredient</a>
          </li>
          <li>
            <a class="txt-btn" href="{% url 'recipe:add_step' recipe.id %}">Add step</a>
          </li>
        </ul>
        <ul>
          <li>
            {% include "includes/recipe/forms/delete_recipe.html" %}
          </li>
        </ul>
    </nav>
  {% endif %}
{% endblock %}

{% block content %}
	<h1>{{ recipe.name }}</h1>
	<h3>{{ recipe.brew_category.name }}</h3>
  <ul>
    <li>Created {{ recipe.pub_date }}
      {% if recipe.created_by %}
        by {{ recipe.created_by }} 
      {% endif %}</li>
  </ul>

	<ul>
    {% if recipe.original_gravity %}
      <li>OG: {{ recipe.original_gravity }}</li>
    {% endif %}
    {% if recipe.final_gravity %}
      <li>FG: {{ recipe.final_gravity }}</li>
    {% endif %}
    {% if recipe.ph %}
      <li>PH: {{ recipe.ph }}</li>
    {% endif %}
      <li>ABV: {{ recipe.calculate_abv }}%</li>
	</ul>
  <hr>
	<h3>Ingredients</h3>
  {% if ingredients %}
    <ul>
    {% for in_recipe in ingredients %}
      <li>
        <h4>{{ in_recipe.ingredient.name }}</h4>
        <h5>{{ in_recipe.ingredient.category }}</h5>
        <h5><i>by {{ in_recipe.ingredient.manufacturer.name }}</i></h5>
        {% if in_recipe.ingredient.description %}
          <i>{{ in_recipe.ingredient.description }}</i>
        {% endif %}
        <p>{{ in_recipe.amount }} {{ in_recipe.amount_unit|lower }}</p>
        {% if user == recipe.created_by and in_recipe.amount_left %}
          <p>Unused in recipe: {{ in_recipe.amount_left }} {{ in_recipe.amount_unit|lower }}</p>
        {% endif %}
        <form class="inline" method="post" action="{% url 'recipe:delete_ingredient_from_recipe' recipe.id in_recipe.id %}" onsubmit="return confirm('Do you really want to remove {{ in_recipe.ingredient.name }} from this recipe?');">
          {% csrf_token %}
          <input type="submit" value="Remove"/>
        </form>        
        <a class="btn" href="{% url 'recipe:edit_ingredient_in_recipe' recipe.id in_recipe.id %}">Edit</a>
      </li>
    {% endfor %}
    </ul>
  {% endif %}
  <hr>
  <section>
	<h3>Steps</h3>
  {% if steps %}
    <ul>
    {% for step_and_form in steps_and_forms %}
      <li class="edit step">
        <h4>#{{ step_and_form.step.order|add:"1" }} {{ step_and_form.step.category }}</h4>
        <p><i>{{ step_and_form.step.format_duration }}</i></p>

        {% if user == recipe.created_by %}
          <form class="inline" method="post" action="{% url 'recipe:move_step' recipe.id step_and_form.step.id %}">
            {% csrf_token %}
            <input type="hidden" name="action" value="up"/>
            <input type="submit" value="Move up"/>
          </form>

          <form class="inline" method="post" action="{% url 'recipe:move_step' recipe.id step_and_form.step.id %}">
            {% csrf_token %}
            <input type="hidden" name="action" value="down"/>
            <input type="submit" value="Move down"/>
          </form>

          <form method="post" action="{% url 'recipe:move_step' recipe.id step_and_form.step.id %}">
            {% csrf_token %}
            <input type="hidden" name="action" value="arbitrary"/>
            <select name="move_to">
              {% for step_and_form in steps_and_forms %}
              <option value="{{ step_and_form.step.order }}">{{ step_and_form.step.order|add:"1" }}</option>
              {% endfor %}
            </select>
            <input type="submit" value="Move to spot"/>
          </form>

          <form method="post" action="{% url 'recipe:delete_step' recipe.id step_and_form.step.id %}" onsubmit="return confirm('Do you really want to delete {{ step_and_form.step.category.name }}?');">
            {% csrf_token %}
            <input type="submit" value="Delete"/>
          </form>        
          <form method="post">
            {% csrf_token %}
            <li>
              <input type="hidden" name="step" value="{{ step_and_form.step.id }}"/>
              <label for="id_ingredient">Ingredient:</label>
              <select name="ingredient" id="id_ingredient">
                <option value="" disabled selected>Choose ingredient</option>
                {% for ingredient in ingredients %}
                  {% if ingredient.amount_left %}
                    <option value="{{ ingredient.id }}" data-amount_unit="{{ ingredient.amount_unit|lower }}" data-amount="{{ ingredient.amount_left }}">{{ ingredient }}</option>
                  {% endif %}
                {% endfor %}
              </select>
            </li>
            <li>
              <label for="id_amount">Amount:</label>
              <input type="number" name="amount" step="0.1" min="0.0" max="{{ ingredient.amount_left }}" required id="id_amount"> <span id="amount_unit">liter</span>
            </li>
            <input type="submit" value="Add ingredient"/>
          </form>

        {% endif %}

        {% if step_and_form.step.ingredientinstep_set.exists %}
          <h4>Ingredients</h4>
          <ul>
          {% for ingredient in step_and_form.step.ingredientinstep_set.all %}
          <li>{{ ingredient.amount }} {{ ingredient.ingredient.amount_unit|lower }} of {{ ingredient.ingredient.ingredient.name }} by {{ ingredient.ingredient.ingredient.manufacturer.name }}</li>
          <form method="post" action="{% url 'recipe:delete_ingredient_from_step' recipe.id ingredient.id %}" onsubmit="return confirm('Do you really want to remove {{ ingredient.ingredient.ingredient.name }} from the {{ step_and_form.step.category.name|lower }} step?');">
            {% csrf_token %}
            <input type="submit" value="Remove"/>
          </form>        
          {% endfor %}
          </ul>
        {% endif %}

        <form method="post" action="{% url 'recipe:edit_step_description' recipe.id step_and_form.step.id %}">
          {% csrf_token %}
          {{ step_and_form.form }}
          <input type="submit" value="Save"/>
        </form>

      </li>
    {% endfor %}
    </ul>
  {% endif %}
  </section>

{% endblock %}

templates/recipe/index.html
{% extends "base.html" %}

{% block title %}
{{ block.super }} - {{ title }}
{% endblock %}

{% block sub_nav %}
{% include "recipe/nav.html" %}
{% endblock %}

{% block content %}
	{% if recipes %}
		<ul class="recipe_list">
		{% for recipe in recipes %}
				<li class="__single_recipe"><a href="{% url 'recipe:detail' recipe.id %}">{{ recipe.name }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No recipes are available.</p>
	{% endif %}
{% endblock %}

templates/recipe/nav.html
{% if user.is_authenticated %}
  <li><a href="{% url 'recipe:created_recipes' %}">My recipes</a></li>
  |
  <li><a href="{% url 'recipe:created_ingredients' %}">Available ingredients</a></li>
{% endif %}