ekrubrygg/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

ekrubrygg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from .core.urls import urlpatterns as core_urls
from .recipe.urls import urlpatterns as recipe_urls
from .account.urls import urlpatterns as account_urls

from .account.views import profile as profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_urls)),
    path('recipe/', include((recipe_urls, 'recipe'), namespace='recipe')),
    path('accounts/profile/', profile_view, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load static %}
{% load i18n %}
{% load account socialaccount %}
<!DOCTYPE html>
<html>
	<head>
    <title>{% block title %}Ekrubrygg{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  {% include "includes/jquery.html" %}
  {% block javascripts %}{% endblock %}
	</head>
	<body>
    <header>
      <nav class="main">
        <ul>
          <a href="{% url 'index' %}"><li>HOME</li></a>
          <a href="{% url 'recipe:index' %}"><li>RECIPES</li></a>
        </ul>
      </nav>
      {% block admin_nav %}{% endblock %}
    </header>
    <nav id="sub">
      <ul class="left">
        {% if not user.is_authenticated %}
        <li><a href="{% url 'account_login' %}">Sign in</a></li>
        |
        <li><a href="{% url 'account_signup' %}">Register</a></li>
        {% else %}
          <li>Logged in as <a href="{% url 'profile' %}">{{ user }}</a></li>
          |
          <li>
            <form method="post" action="{% url 'account_logout' %}" novalidate>
              {% csrf_token %}
              <input class="txt-btn" type="submit" value="Logout"/>
            </form>
          </li>
        {% endif %}
      </ul>
      <ul class="center">
        {% block center_nav %}{% endblock %}
      </ul>
      <ul class="right">
        {% if user.is_authenticated %}
          {% include "recipe/nav.html" %}
        {% endif %}
      </ul>
    </nav>
    <main>
      {% if messages %}
        <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
      {% block content %}{% endblock %}
    </main>
	</body>
</html>